language: python
cache: pip
python:
  - "3.5"
before_install:
  - "mv secrets.yaml.sample secrets.yaml"
  - "mkdir ssl"
  - "touch ssl/fullchain.pem"
  - "touch ssl/privkey.pem"
install:
  - pip3 install homeassistant
  - git clone https://github.com/claytonjn/hass-circadian_lighting.git circadian_lighting_component/
  - mv circadian_lighting_component/custom_components ./custom_components
  - git clone https://github.com/StyraHem/ShellyForHASS.git shelly_component/
  - mv shelly_component/custom_components ./custom_components
script:
  - "hass --version"
  - "ls"
  - "cd custom_components && ls -al"
  - "cd .."
  - "hass -c $(pwd) --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"' 