language: python
cache: pip

# safelist
branches:
  only:
  - master
  - travis-fixing

python:
  - "3.5"

before_install:
  - "mv secrets.yaml.sample secrets.yaml"
  - "sudo mkdir /ssl"
  - "sudo touch /ssl/fullchain.pem"
  - "sudo touch /ssl/privkey.pem"

install:
  - pip3 install homeassistant
  - git clone https://github.com/claytonjn/hass-circadian_lighting.git circadian_lighting_component
  - mv circadian_lighting_component/custom_components custom_components
  - git clone https://github.com/StyraHem/ShellyForHASS.git shelly_component
  - mv shelly_component/custom_components/* custom_components
  - rm custom_components/shelly/__init__.py
  - touch custom_components/shelly/__init__.py

script: 
  - "hass --version"
  - "ls"
  - "hass -c $(pwd) --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"' 