language: python
cache: pip
python:
  - "3.5"
before_install:
  - "mv secrets.yaml.sample secrets.yaml"
  - "mkdir /ssl"
  - "touch /ssl/fullchain.pem"
  - "touch /ssl/privkey.pem"
install:
  - pip3 install homeassistant
script:
  - "pwd"
  - "whoami"
  - "hass --version"
  - "ls"
  - "cd custom_components && ls -al"
  - "cd shelly && ls -al"
  - "cd ../.."
  - "hass -c $(pwd) --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"' 